services:
    caddy:
        image: caddy:latest
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./screencast.mp4:/srv/video/screencast.mp4
            - frontend_dist:/srv/client
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - app-network

    frontend:
        build:
            context: ./apps/client
            dockerfile: Dockerfile
            args:
                VITE_ENDPOINT: ${VITE_ENDPOINT} # http://127.0.0.1/api
        env_file:
            - .env
        volumes:
            - frontend_dist:/app/dist
        networks:
            - app-network

    backend:
        build:
            context: ./apps
            dockerfile: ./backend/Dockerfile
        volumes:
            - static_uploads:/app/uploads
        ports:
            - "8000:8000"
        environment:
            - ENV=production
        networks:
            - app-network
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]

volumes:
    caddy_data:
    caddy_config:
    frontend_dist:
    static_uploads:

networks:
    app-network:
        driver: bridge
